export const reducerCases = {
    SET_USER_INFO: "SET_USER_INFO",
    SET_NEW_USER: "SET_NEW_USER",
    SET_ALL_CONTACTS_PAGE: "SET_ALL_CONTACTS_PAGE",
    CHANGE_CURRECT_CHAT_USER: "CHANGE_CURRECT_CHAT_USER",
    SET_MESSAGES: "SET_MESSAGES",
    SET_SOCKET: "SET_SOCKET",
    ADD_MESSAGES: "ADD_MESSAGES",
    SET_MESSAGES_SEARCH: "SET_MESSAGES_SEARCH",
    SET_USER_CONTACTS: "SET_USER_CONTACTS",
    SET_ONLINE_USERS: "SET_ONLINE_USERS",
    SET_CONTACT_SEARCH: "SET_CONTACT_SEARCH",
}